---
title: "JapDrama"
output: html_document
---
# Text Mining

### 2018.07.17

## 網路爬蟲

```{r}
source('pttTestFunction.R')

id = c(1850:1857)
URL = paste0("https://www.ptt.cc/bbs/Japandrama/index", id, ".html")
filename = paste0(id, ".txt")
pttTestFunction(URL[1], filename[1])
mapply(pttTestFunction,
       URL = URL, filename = filename)
rm(list=ls(all.names = TRUE))

```

## 文本清理
```{r}
rm(list=ls(all.names = TRUE))
library(NLP)
library(tm)
library(jiebaRD)
library(jiebaR)
library(RColorBrewer)
library(wordcloud)

filenames <- list.files(getwd(), pattern="*.txt")
files <- lapply(filenames, readLines)
docs <- Corpus(VectorSource(files))

#移除可能有問題的符號

toSpace <- content_transformer(function(x, pattern) {
    return (gsub(pattern, " ", x))
  })

docs <- tm_map(docs, toSpace, "※")
docs <- tm_map(docs, toSpace, "去")
docs <- tm_map(docs, toSpace, "覺得")
docs <- tm_map(docs, toSpace, "自己")
docs <- tm_map(docs, toSpace, "啦")
docs <- tm_map(docs, toSpace, "可能")
docs <- tm_map(docs, toSpace, "沒")
docs <- tm_map(docs, toSpace, "嗎")
docs <- tm_map(docs, toSpace, "跟")
docs <- tm_map(docs, toSpace, "好")
docs <- tm_map(docs, toSpace, "真")
docs <- tm_map(docs, toSpace, "讓")
docs <- tm_map(docs, toSpace, "說")
docs <- tm_map(docs, toSpace, "很")
docs <- tm_map(docs, toSpace, "◆")
docs <- tm_map(docs, toSpace, "‧")
docs <- tm_map(docs, toSpace, "就")
docs <- tm_map(docs, toSpace, "不")
docs <- tm_map(docs, toSpace, "在")
docs <- tm_map(docs, toSpace, "會")
docs <- tm_map(docs, toSpace, "人")
docs <- tm_map(docs, toSpace, "吧")
docs <- tm_map(docs, toSpace, "還")
docs <- tm_map(docs, toSpace, "時間")
docs <- tm_map(docs, toSpace, "一個")
docs <- tm_map(docs, toSpace, "也")
docs <- tm_map(docs, toSpace, "噓")
docs <- tm_map(docs, toSpace, "都")
docs <- tm_map(docs, toSpace, "只")
docs <- tm_map(docs, toSpace, "而")
docs <- tm_map(docs, toSpace, "又")
docs <- tm_map(docs, toSpace, "什麼")
docs <- tm_map(docs, toSpace, "已經")
docs <- tm_map(docs, toSpace, "非常")
docs <- tm_map(docs, toSpace, "應該")
docs <- tm_map(docs, toSpace, "大家")
docs <- tm_map(docs, toSpace, "要")
docs <- tm_map(docs, toSpace, "們")
docs <- tm_map(docs, toSpace, "現")
docs <- tm_map(docs, toSpace, "但")
docs <- tm_map(docs, toSpace, "的")
docs <- tm_map(docs, toSpace, "看")
docs <- tm_map(docs, toSpace, "她")
docs <- tm_map(docs, toSpace, "因為")
docs <- tm_map(docs, toSpace, "為")
docs <- tm_map(docs, toSpace, "和")
docs <- tm_map(docs, toSpace, "對")
docs <- tm_map(docs, toSpace, "喜歡")
docs <- tm_map(docs, toSpace, "這")
docs <- tm_map(docs, toSpace, "我")
docs <- tm_map(docs, toSpace, "是")
docs <- tm_map(docs, toSpace, "其實")
docs <- tm_map(docs, toSpace, "根本")
docs <- tm_map(docs, toSpace, "被")
docs <- tm_map(docs, toSpace, "像")
docs <- tm_map(docs, toSpace, "編輯")
docs <- tm_map(docs, toSpace, "看板")
docs <- tm_map(docs, toSpace, "推")
docs <- tm_map(docs, toSpace, "有")
docs <- tm_map(docs, toSpace, "了")
docs <- tm_map(docs, toSpace, "你")
docs <- tm_map(docs, toSpace, "標題")
docs <- tm_map(docs, toSpace, "可以")
docs <- tm_map(docs, toSpace, "他")
docs <- tm_map(docs, toSpace, "看")
docs <- tm_map(docs, toSpace, "個")
docs <- tm_map(docs, toSpace, "以為")
docs <- tm_map(docs, toSpace, "啊")
docs <- tm_map(docs, toSpace, "到")
docs <- tm_map(docs, toSpace, "想")
docs <- tm_map(docs, toSpace, "發信站")
docs <- tm_map(docs, toSpace, "批踢踢實業坊")
docs <- tm_map(docs, toSpace, "[a-zA-Z]")

#移除標點符號 (punctuation)

#移除數字 (digits)、空白 (white space)

docs <- tm_map(docs, removePunctuation)
docs <- tm_map(docs, removeNumbers)
docs <- tm_map(docs, stripWhitespace)
```

## 詞頻矩陣
```{r}
mixseg = worker()
jieba_tokenizer=function(d){
  unlist(segment(d[[1]],mixseg))
}
seg = lapply(docs, jieba_tokenizer)
freqFrame = as.data.frame(table(unlist(seg)))
freqFrame = freqFrame[order(freqFrame$Freq,decreasing=TRUE), ]
library(knitr)
kable(head(freqFrame), format = "markdown")
```

## 文字雲
```{r}
wordcloud(freqFrame$Var1,freqFrame$Freq,
          scale=c(5,0.1),min.freq=50,max.words=150,
          random.order=TRUE, random.color=FALSE, 
          rot.per=.1, colors=brewer.pal(8, "Dark2"),
          ordered.colors=FALSE,use.r.layout=FALSE,
          fixed.asp=TRUE)
```
<br>
### 可以看出今年的日劇中，日版版流星花園(花過天晴)中的男主角『天馬」，討論度非常高。
